name: "Build - action"

on: [push, pull_request]

jobs:
  build-docker-image:
    name: "ImageOptimApi Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create environment file
        run: echo NUGET_API_KEY=${{ secrets.NUGET_API_KEY }} >> release.env

      - name: Run build.bash
        env:
          BLD_DOCKER_IMAGE: imageoptimapi
          CR_OWNER: ${{secrets.CR_OWNER}}
          CR_PASSWORD: ${{secrets.CR_PASSWORD}}
          CR_USER: ${{secrets.CR_USER}}
          GHCR_OWNER: ${{secrets.GHCR_OWNER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash -p

      - uses: actions/upload-artifact@v3
        with:
          path: package/ImageOptimApi.*.nupkg
          if-no-files-found: ignore
